FROM sagcr.azurecr.io/webmethods-edge-runtime:11.0.0.2

COPY --chown=sagadmin:sagadmin ./wpm/ /opt/softwareag/wpm/
COPY --chown=sagadmin:sagadmin ./wpm/wpm.yml /opt/softwareag/wpm/wpm.yml

USER root
WORKDIR /opt/softwareag/wpm
RUN /opt/softwareag/wpm/bin/wpm.sh install -r custom_bitbucket wmio-cicd

RUN /opt/softwareag/wpm/bin/wpm.sh install -r default -j <SAG REPO TOKEN> -wr softwareag WmJDBCAdapter
WORKDIR /
ENV SAG_IS_CLOUD_REGISTER_URL https://psdev.int-aws-de.webmethods.io
ENV SAG_IS_EDGE_CLOUD_ALIAS EdgeRuntime_Hybrid_IPaaS_Product
ENV SAG_IS_CLOUD_REGISTER_TOKEN <Cloud Token>